---
- name: allow JBoss EAP ports
  shell: "systemctl stop firewalld ; systemctl stop firewalld ; systemctl disable firewalld ; setenforce 0 ; subscription-manager clean"

- name: Registering and attaching subscriptions
  redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    pool_ids:
      - 8a85f99c69d235390169ed7add29150a
      - 8a85f99c69d235390169ed7a937314e9

- name: enable repos
  shell: subscription-manager repos --enable={rhel-7-server-rpms,rhel-7-server-extras-rpms}

- name: Installing Pre-requirements
  yum:
    name: "{{ item }}"
    state: present 
  loop:
    - java-1.8.0-openjdk
    - unzip

- name: Unpacking Package
  shell: "unzip {{ zip_path }} -d {{ install_path }}"

- name: Initial JBoss Config
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  loop:
    - variable.txt
    
- name: Configurating server address
  template:
    src: standalone.xml
    dest: "{{ install_path }}/jboss-eap-7.2/standalone/configuration/standalone.xml"

- name: enable a user for administration
  shell: "echo 'smanager=de8f0550922a4d6aa2682ba8d8e4d35b' >> {{ install_path }}/jboss-eap-7.2/standalone/configuration/mgmt-users.properties ; echo 'smanager=' >> {{ install_path }}/jboss-eap-7.2/standalone/configuration/mgmt-groups.properties"

- name: Set JVA_OPTS variable
  shell: "cat /tmp/variable.txt >> {{ install_path }}/jboss-eap-7.2/bin/standalone.conf"

- name: Configuring JBoss EAP as a Service in Red Hat Enterprise Linux
  shell: "echo JBOSS_HOME={{ install_path }} >> {{ install_path }}/jboss-eap-7.2/bin/init.d/jboss-eap.conf ; echo JBOSS_USER=root >> {{ install_path }}/jboss-eap-7.2/bin/init.d/jboss-eap.conf ; cp {{ install_path }}/jboss-eap-7.2/bin/init.d/jboss-eap.conf /etc/default ; cp {{ install_path }}/jboss-eap-7.2/bin/init.d/jboss-eap-rhel.sh /etc/init.d ; chmod +x /etc/init.d/jboss-eap-rhel.sh ; chkconfig --add /etc/init.d/jboss-eap-rhel.sh"

- name: Creating JBoss EAP Daemon
  shell: "ln -s /opt/jboss-eap-7.2 /usr/bin/jboss-eap-7.2"

- name: Configurating JBoss EAP as a Service
  template:
    src: pluizetto-jboss-eap-7.2.service
    dest: /usr/lib/systemd/system/pluizetto-jboss-eap-7.2.service

- name: Reload list of Daemons
  shell: systemctl daemon-reload
  
- name: Enable pluizetto-jboss-eap-7.2.service
  systemd:
    name: pluizetto-jboss-eap-7.2.service
    state: stopped
    enabled: yes

- name: Starting JBoss EAP
  shell: init 6
  
- pause:
   minutes: 1

- name: Open JBoss EAP UI
  shell: "sleep 60 ; bash /home/pluizetto/firefox.sh &"
  delegate_to: 192.168.10.1
...
