---
- name: rollback snapshot vm01
  shell: 'virsh snapshot-revert --snapshotname 000 --domain target01'
  delegate_to: 192.168.10.1
  
- name: rollback snapshot vm01
  command: 'virsh snapshot-revert --snapshotname 001 --domain target02'
  delegate_to: 192.168.10.1
  
- name: Install Apache Webserver
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    
- name: Configurating Firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: yes
    state: enabled
  loop:
    - http
    - https

- name: configure apache page
  template:
    src: index.html.template
    dest: /var/www/html/index.html

- name: configure SELinux
  shell: 'restorecon -R /var/www/'

- name: Start Apache Webserver
  systemd:
    name: httpd
    state: restarted 
    enabled: yes

- debug:
    msg: Please, access http://{{ ansible_default_ipv4.address }} ;D
...
