---
- name: rollback snapshot vm01
  shell: 'virsh snapshot-revert --snapshotname 000 --domain target01'
  delegate_to: 192.168.10.1
  
- name: rollback snapshot vm01
  command: 'virsh snapshot-revert --snapshotname 001 --domain target02'
  delegate_to: 192.168.10.1
  
- name: Deploy Apache Webserver
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - subscribe_hosts
    - apache_webserver
...
