--- 
- name: rollback snapshot vm01
  shell: 'virsh snapshot-revert --snapshotname 000 --domain target01'
  delegate_to: 192.168.10.1
  
- name: rollback snapshot vm02
  command: 'virsh snapshot-revert --snapshotname 001 --domain target02'
  delegate_to: 192.168.10.1
  
- name: clean registers
  shell: subscription-manager clean

- name: Registering and attaching subscriptions
  redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    pool_ids:
      - 8a85f999710f3aea01714e02cf976360

- name: enable repos
  shell: subscription-manager repos --enable=rhel-7-server-rpms

- name: repolist
  shell: yum repolist
...
