---
- name: copy tzdata
  copy:
    src: /root/tzdata-2019c-1.el7.noarch.rpm
    dest: /root/
    
- name: update tzdata
  yum:
    name: /root/tzdata-2019c-1.el7.noarch.rpm
    state: latest
    
- name: clean registers
  shell: subscription-manager clean

- name: Registering and attaching subscriptions
  redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    pool_ids:
      - 8a85f99c69d235390169ed7add29150a 

- name: enable repos
  shell: subscription-manager repos --enable=rhel-7-server-rpms
...
